id_self:                req_frontline_solar_buffer_kit_cr_ingress_protection
guid_self:              req_b4c757f51a1e477aab1c9a92b587585b
copyright:              Copyright 2026 William Payne
license:                Apache-2.0

protective_mark:

  - id_mark:            mark_public
    guid_mark:          mark_0c96ccb7b7534574acf6ed42f9deba0f

title:                  Ingress protection
statement:              |
                        The Frontline_Battery_Crate shall achieve a
                        minimum ingress protection rating of IP65 in
                        its closed state.
rationale:              |
                        Protection against dust and water jets is
                        necessary to maintain function in harsh
                        frontline environments.
category:               form
status:                 proposed

relation:

  - id_relation:        r_is_derived_from
    guid_relation:      r_a8017d991f8a4e63a84d1eec5a2d6051
    id_target:          cpt_frontline_solar_buffer_kit
    guid_target:        cpt_1b61ed7c617443c3b60bb6b0d5d8e29c

  - id_relation:        r_is_derived_from
    guid_relation:      r_a8017d991f8a4e63a84d1eec5a2d6051
    id_target:          need_frontline_multiday_offgrid_power
    guid_target:        need_0faac913d77d46468f29830da1b94a1d
